import { SignInButton, useUser } from "@clerk/nextjs";
import {
  Box,
  Button,
  Container,
  ImageListItem,
  TextField,
  Typography,
} from "@mui/material";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";
import Image from "next/image";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { Loading } from "~/components/loading";
import { useState } from "react";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  const [input, setInput] = useState("");

  const ctx = api.useContext();

  const { mutate, isLoading: isPosting } = api.posts.create.useMutation({
    onSuccess: () => {
      setInput("");
      void ctx.posts.getAll.invalidate();
    }
  });

  console.log(user);

  if (!user) return null;
  return (
    <Box
      sx={{
        display: "flex",
        width: "100%",
      }}
    >
      <ImageListItem sx={{ marginRight: 2, height: 56, width: 56 }}>
        <Image
          src={user?.profileImageUrl}
          alt="profileImage"
          style={{ borderRadius: "50%" }}
          width={56}
          height={56}
        />
      </ImageListItem>
      <TextField
        sx={{
          input: { color: "white" },
          label: { color: "white" },
          flexGrow: 1,
        }}
        label="Type some emojis!"
        variant="standard"
        color="primary"
        value={input}
        onChange={(e) => setInput(e.target.value)}
        disabled={isPosting}
      />
      <Button variant="outlined" onClick={() => mutate({ content: input })}>
        Post
      </Button>
    </Box>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <Box
      key={post.id}
      sx={{
        p: 4,
        border: 1,
        borderColor: "rgb(148 163 184)",
        display: "flex",
      }}
    >
      <ImageListItem sx={{ marginRight: 2, height: 56, width: 56 }}>
        <Image
          src={author.profileImageUrl}
          alt={`@${author.username}'s profile picture`}
          style={{ borderRadius: "50%" }}
          width={56}
          height={56}
        />
      </ImageListItem>
      <Box sx={{ display: "flex", flexDirection: "column" }}>
        <Box sx={{ color: "#cbd5e1", display: "flex", alignItems: "center" }}>
          <Typography
            variant="body1"
            sx={{ marginRight: 1 }}
          >{`@${author.username}`}</Typography>
          <Typography variant="body2">{`· ${dayjs(
            post.createdAt
          ).fromNow()}`}</Typography>
        </Box>
        <Box component="span">
          <Typography variant="h6">{post.content}</Typography>
        </Box>
      </Box>
    </Box>
  );
};

const Feed = () => {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();

  if (postsLoading) return <Loading />;

  if (!data) return <div>Something went wrong</div>;

  return (
    <Box
      sx={{
        display: "flex",
        flexDirection: "column",
      }}
    >
      {data.map((fullPost) => (
        <PostView {...fullPost} key={fullPost.post.id} />
      ))}
    </Box>
  );
};

const Home: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  api.posts.getAll.useQuery();

  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container
          maxWidth="md"
          sx={{
            height: "100vh",
          }}
        >
          <Box
            sx={{
              height: "100%",
              border: 1,
              borderColor: "rgb(148 163 184)",
            }}
          >
            <Box
              sx={{
                border: 1,
                borderColor: "rgb(148 163 184)",
                p: 2,
              }}
            >
              {!isSignedIn && (
                <Box className="flex justify-center">
                  <SignInButton />
                </Box>
              )}
              {isSignedIn && <CreatePostWizard />}
            </Box>
            <Feed />
          </Box>
        </Container>
      </main>
    </>
  );
};

export default Home;
